<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>correction</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="./css/style.css" rel="stylesheet">
</head>

<body>
    <main class="container ">
        <h1 class="text-center"> Ma TODOLIST :) </h1>

        <div class="taches">
            <div class="tache">
                <input type="checkbox"> <span> Mort aux rats pour chat coisins </span>
                <p>description</p>
            </div>
            <div class="tache">
                <input type="checkbox"> <span> Mort aux rats pour chat coisins </span>
                <p>description</p>
            </div>
            <div class="tache">
                <input type="checkbox"> <span> Mort aux rats pour chat coisins </span>
                <p>description</p>
            </div>
        </div>


        <h2 class="text-center"> Nouvelle tâche </h2>
        <form method="POST" action="./php/add.php">

            <div class="mb-3">
                <label for="titre" class="form-label">Titre</label>
                <input type="text" name="titre" class="form-control ms-3" id="titre" placeholder="Ajouter le titre de la tache">
            </div>
            <div class="mb-3">
                <label for="desc" class="form-label">desc</label>
                <textarea class="form-control ms-3" name="desc" id="desc" placeholder="Ajouter le titre de la tache"></textarea>
            </div>

            <div class="mb-3">
                <label for="date" class="form-label">date de fin</label>
                <div class="lineselect ms-3">
                    <select name="jour" class="form-select" aria-label="Default select example">
                    <?php for($i = 1; $i <= 31 ; $i++): ?>
                        <option value=<?= ''.$i.'' ?>> <?= $i ?></option>
                        <?php endfor ?>
                    </select>
                    <select name="mois" class="form-select" aria-label="Default select example">
                    <?php for($i = 1; $i <= 12 ; $i++): ?>
                        <option value=<?= ''.$i.'' ?>> <?= $i ?></option>
                        <?php endfor ?>
                    </select>

                    <select name="annee" class="form-select" aria-label="Default select example">
                    <?php for($i = date("Y"); $i <= date('Y')+10 ; $i++): ?>
                        <option value=<?= ''.$i.'' ?>> <?= $i ?></option>
                        <?php endfor ?>
                    </select>
                </div>

                <div class="mb-3  mt-5 text-center">
                    <label for="prio" class="form-label ">priorité</label>
                    <div class="ml-3 ms-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input mx-1" type="radio" name="prio" id="basse" value="option1" checked>
                            <label class="form-check-label" for="basse">
                                basse
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input mx-1" type="radio" name="prio" id="normal" value="option2">
                            <label class="form-check-label" for="normal">
                                normal
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input mx-1" type="radio" name="prio" id="urgent" value="option3">
                            <label class="form-check-label" for="urgent">
                                urgent
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-auto mt-5 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            </div>





        </form>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</html>